### ISSUE TITLE
Does Grove Pi + support controlling avr serial port(D0, D1) with Python?

### ISSUE THREAD

**Issue by jerryyip** [DexterInd/GrovePi#371]
I could not find any API to control the AVR serial(how to control the TX pin)?

**Comment by RobertLucian** [comment]
I'm afraid you can't-do this with our API. We didn't do a support for it because:

1. The Pi already has a serial port and we've named it `RPISER` on the GrovePi board.
2. The AVR's serial can be a bit tricky to work with especially when it's bridged by I2C.

With that being said, I think it would have been a cool feature provided the Pi hadn't had one.
